import type { Student } from './definitions';

export const students: Student[] = [
  {
    id: '1',
    grNo: '1001',
    studentName: 'Ahmed Khan',
    fatherName: 'Zahid Khan',
    caste: 'Khan',
    bForm: '12345-6789012-3',
    dateOfBirth: new Date('2010-05-15'),
    religion: 'Islam',
    admissionDate: new Date('2022-08-01'),
    cnic: 'N/A',
    guardianName: 'Zahid Khan',
    guardianCnic: '32102-1234567-8',
    relationshipWithGuardian: 'Father',
    contactNo: '0300-1234567',
    disability: 'None',
    vaccine: 'Yes',
    classStudying: '5',
    section: 'A',
    newEnrolReEnrol: 'New Enrol',
    remarks: 'A bright student.',
    dateOfLeaving: null,
    reasonOfLeaving: '',
    progress: 'Excellent',
    conduct: 'Good',
    grade: 'A+',
  },
  {
    id: '2',
    grNo: '1002',
    studentName: 'Bilal Ahmed',
    fatherName: 'Ali Raza',
    caste: 'Mughal',
    bForm: '23456-7890123-4',
    dateOfBirth: new Date('2011-02-20'),
    religion: 'Islam',
    admissionDate: new Date('2022-08-01'),
    cnic: 'N/A',
    guardianName: 'Ali Raza',
    guardianCnic: '32102-8765432-1',
    relationshipWithGuardian: 'Father',
    contactNo: '0321-9876543',
    disability: 'None',
    vaccine: 'Yes',
    classStudying: '4',
    section: 'B',
    newEnrolReEnrol: 'New Enrol',
    remarks: '',
    dateOfLeaving: null,
    reasonOfLeaving: '',
    progress: 'Good',
    conduct: 'Excellent',
    grade: 'A',
  },
];
