import type { Student } from './definitions';

export const students: Student[] = [
  {
    id: '1',
    grNo: '1001',
    studentName: 'Ahmed Khan',
    fatherName: 'Zahid Khan',
    raceAndCaste: 'Khan',
    bForm: '12345-6789012-3',
    placeOfBirth: 'Hyderabad',
    dateOfBirth: new Date('2010-05-15'),
    dateOfBirthInWords: 'Fifteenth May Two Thousand Ten',
    religion: 'Islam',
    lastSchoolAttended: 'Little Folks School',
    admissionDate: new Date('2022-08-01'),
    classInWhichAdmitted: '4',
    cnic: 'N/A',
    guardianName: 'Zahid Khan',
    guardianCnic: '32102-1234567-8',
    relationshipWithGuardian: 'Father',
    contactNo: '0300-1234567',
    disability: 'None',
    vaccine: 'Yes',
    classStudying: '5',
    section: 'A',
    newEnrolReEnrol: 'New Enrol',
    remarks: 'A bright student.',
    dateOfLeaving: null,
    reasonOfLeaving: 'Passed S.S.C Part-II Annual',
    examination: 'S.S.C Part-II Annual',
    underSeatNo: '12345',
    progress: 'Excellent',
    conduct: 'Good',
    grade: 'A+',
  },
  {
    id: '2',
    grNo: '1002',
    studentName: 'Bilal Ahmed',
    fatherName: 'Ali Raza',
    raceAndCaste: 'Mughal',
    bForm: '23456-7890123-4',
    placeOfBirth: 'Karachi',
    dateOfBirth: new Date('2011-02-20'),
    dateOfBirthInWords: 'Twentieth February Two Thousand Eleven',
    religion: 'Islam',
    lastSchoolAttended: 'City School',
    admissionDate: new Date('2022-08-01'),
    classInWhichAdmitted: '3',
    cnic: 'N/A',
    guardianName: 'Ali Raza',
    guardianCnic: '32102-8765432-1',
    relationshipWithGuardian: 'Father',
    contactNo: '0321-9876543',
    disability: 'None',
    vaccine: 'Yes',
    classStudying: '4',
    section: 'B',
    newEnrolReEnrol: 'New Enrol',
    remarks: '',
    dateOfLeaving: null,
    reasonOfLeaving: 'Passed S.S.C Part-II Annual',
    examination: 'S.S.C Part-II Annual',
    underSeatNo: '54321',
    progress: 'Good',
    conduct: 'Excellent',
    grade: 'A',
  },
];
