export type Student = {
  id: string;
  grNo: string;
  studentName: string;
  fatherName: string;
  raceAndCaste: string;
  bForm: string;
  placeOfBirth: string;
  dateOfBirth: Date;
  dateOfBirthInWords: string;
  religion: string;
  lastSchoolAttended: string;
  admissionDate: Date;
  classInWhichAdmitted: string;
  cnic: string;
  guardianName: string;
  guardianCnic: string;
  relationshipWithGuardian: string;
  contactNo: string;
  disability: string;
  vaccine: 'Yes' | 'No';
  classStudying: string;
  section: string;
  newEnrolReEnrol: 'New Enrol' | 'Re-Enrol';
  remarks: string;
  dateOfLeaving?: Date | null;
  reasonOfLeaving: string;
  examination: string;
  underSeatNo: string;
  progress: 'Excellent' | 'Good' | 'Average' | 'Poor';
  conduct: 'Excellent' | 'Good' | 'Average' | 'Poor';
  grade: string;
  sscType?: 'SSC I' | 'SSC II';
  sscRollNo?: string;
};

export const certificateTypes = ['Appearance', 'Character', 'Pass', 'School Leaving'] as const;
export type CertificateType = typeof certificateTypes[number];
